### ISSUE TITLE
BUG for program size greater than 64K

### ISSUE THREAD

**Issue by stefanofante** [sfyip/STM32F103_MSD_BOOTLOADER#1]
Hello, 
there is a bug for program size greater than 64K 
You need to add a extended linear record (code 04) if the address range exceeded 64K

something like that:
 extended_address = false;
inside the loop:
if (extended_address)
{
print "EXTENDED LINEAR RECORD" with args address >> 16
extended_address = false; 
}

write data records.....
.....
increment address
.....
 if ((address & 0x0000FFFF) == 0)
{
extended_address = true;
}

**Comment by sfyip** [comment]
STM32F103C8T6 is 64 KB flash size, not 128KB. Sorry for the typo. Therefore, the user code only allows ~48KB only.

By default, it supports 32bit extended linear record.
uint32_t address = TRANSFORM_ADDR(address_hi, address_lo); // if extended linear address: ( (((uint32_t)(addr_hi)) << 16) | ((uint32_t)(addr_lo)) )

**Comment by stefanofante** [comment]
I ported the code to STM32F103Z and I faced this problem :-)
To solve the problem I add a piece of code to the pc code in order to manage flash code greater than 64K.
