### ISSUE TITLE
Enhancement: Show file "Drop update.hex here to update firmware.txt"

### ISSUE THREAD

**Issue by tusker-tools** [sfyip/STM32F103_MSD_BOOTLOADER#10]
This bootloader project might be used in a product which is used by people without a deep knowledge about the bootloader usage.

In a situation where the user has activated the bootloader, he could be confused about what to do with the USB drive showing up.
In this case, it could be helpful to show a file named "Drop update.hex here to update firmware.txt". 

The proposal needs the possibility to use long file names in the directory entry. Is this feasable with the current solution?

**Comment by sfyip** [comment]
Ok now. Added readme.txt👍

**Comment by tusker-tools** [comment]
Nice feature 
Thank you for the realization!

**Comment by tusker-tools** [comment]
Realized with f81e518
