### ISSUE TITLE
Crypt firmware not work

### ISSUE THREAD

**Issue by R8CEH** [sfyip/STM32F103_MSD_BOOTLOADER#14]
Hi!  I tested this bootloader and it works well.  But when I use this with an encrypted firmware, the bootloader produces the wrong decryption.  I am reading the firmware from the controller's memory and it does not match the unencrypted firmware.  What am I doing wrong?  I am using APP_ADDR 0x6000, my microcontroller is STM32F103RCT6.  I changed the memory size to 256 kb.

**Comment by sfyip** [comment]
1)Have you tried using tools/hex-crypt to generate the encrypted file?

2) Both the bootloader and hex-crypt use the same AES key and IV.


「Denis Kutuzov (R8CEH) ***@***.***>」在 2023年1月17日 週二，下午8:23 寫道：

**Comment by sfyip** [comment]
Seems I missed to write the extended linear address during across page boundary at line 181 in tools/hex-crypt/hex-crypt.cpp

**Comment by sfyip** [comment]
Yes. I will fix it today. Thanks for the detail information.🙂

**Comment by sfyip** [comment]
Fixed hex-crypt.cpp but not yet tested.
