### ISSUE TITLE
How build external .hex file for your bootloader?

### ISSUE THREAD

**Issue by g1ebati** [sfyip/STM32F103_MSD_BOOTLOADER#18]
Hello, dear friend. The following problem arose: I build your project, did everything as you described in the README file, and the LED from your hex files that are in your repository is blinking successfully.

Next, I tried to generate another hex file. To do this, use __FLASH.ld in :

/* Memories definition */
MEMORY
{
  RAM    (xrw)    : ORIGIN = 0x20000000,   LENGTH = 20K
  FLASH    (rx)    : ORIGIN = 0x08004000,   LENGTH = 48K
}

/* Sections */

but after I put together my project with these changes and got my hex LED flashing file, and using your loader, I didnt get the LED flashing on the bluepill board ((

**Comment by g1ebati** [comment]
Because of this, I also had a question: what are the rules for assembling your hex file for your loader? because after reading the readme, I'm sorry I didn't find it.

**Comment by tusker-tools** [comment]
Hi @g1ebati, there is no special rule for building the application .hex.
Only the applicatoin start address (and length) must match the definition in btldr_config.h.

And of course, the application needs to be configured correctly. This means e.g. that VTOR must be configured according to the start address.

Did you check whether your main application is running correctly when started via debugger (e.g. ST-Link)?

**Comment by g1ebati** [comment]
> And of course, the application needs to be configured correctly. This means e.g. that VTOR must be configured according to the start address.
> 
> Did you check whether your main application is running correctly when started via debugger (e.g. ST-Link)?

Hi @tusker-tools! Yes, main application running correctly)
Thanks, everything worked when I rebuilt the project! And also, in addition to address changes in __FLASH.ld:

/* Memories definition */
MEMORY
{
RAM (xrw) : ORIGIN = 0x20000000, LENGTH = 20K
FLASH (rx) : ORIGIN = 0x08004000, LENGTH = 48K
}

/* Sections */

AND I'm added offset of the interrupt vector table in main.c

int main(void)
{
  /* USER CODE BEGIN 1 */
		__disable_irq();
		  SCB->VTOR = FLASH_BASE | 0x4000;
		  __enable_irq();
  /* USER CODE END 1 */
....
}
it didn't work without this offset)). Thank you very much!

Now I'm trying to change the loader activation button, and I can't do such a simple operation. 
/* Private defines -----------------------------------------------------------*/
//#define BTLDR_EN_Pin LL_GPIO_PIN_0
//#define BTLDR_EN_GPIO_Port GPIOA
/* USER CODE BEGIN Private defines */
#define BTLDR_EN_Pin LL_GPIO_PIN_1
#define BTLDR_EN_GPIO_Port GPIOB
/* USER CODE END Private defines */
It turns out like this: i changed the button in this way, pressed the corresponding pin to the ground, MSD started - but then when dragging the file.hex there was a hangup

**Comment by tusker-tools** [comment]
Cool that you got at least the minimal example running.

Can you confirm that it's really the changed pin which is causing the hangup during .hex flash process? Does it work corractly, if you undo the pin change?
Then I can't imagine a reason for this behavior.

Can you zip your project folder and upload it here (or better create a fork and upload your changes)? I'll try to have a look then.

**Comment by g1ebati** [comment]
Hi @tusker-tools!
Today I got a new board with a new chip and everything worked!! Thank you very much for your help!
