### ISSUE TITLE
New feature: Possibility to activate Bootloader from Application

### ISSUE THREAD

**Issue by tusker-tools** [sfyip/STM32F103_MSD_BOOTLOADER#8]
As soon as the main application is running, there is currently no possibility to jump to the bootloader by software command. Instead, the device must be replugged with button pressed at the same time.

It would be much more comfortable to have the possibility to activate the bootloader from main application. This could be done in the following way:

1. The user sends a "bootloader activation" command in the main app (e.g. by UART)
2. Application jumps to bootloader
3. Bootloader detects firmware update mode request issued by application
4. Bootloader gets activated & enables USB device

I propose to define a new variable stored in a special defined 32bit RAM segment. The application can write a magic number called "bootkey" there.
The bootloader begins execution and checks that variable for presence of the "magic bootkey" in the beginning. If the bootkey is detected, the bootloader is activated.

I already have a working solution for that. But as my solution is for use with GCC compiler, I need some days to adapt that for Keil. Have to learn how to define the bootkey variable section in Keil linker file.

**Comment by sfyip** [comment]
Another method to jump to the bootloader is erase the first FLASH sector at APP_ADDR. 

It can be implemented in main application side. Or this erase routine can be placed at dedicated address (or function lookup table) in bootloader area, main application call this routine to erase the user application.

**Comment by tusker-tools** [comment]
These two ideas from https://github.com/sfyip/STM32F103_MSD_BOOTLOADER/issues/8#issuecomment-1013596901 are quite a good workaround.

But I see two disadvantages:
1. For every reprogramming, we need to perform two flash write operations, one for deleting the beginning of APP_ADDR, one for final reprogramming. This increases the wear of the flash (I know that this is not really a big issue, as STM32 supports 10.000 flash writes)
2. It is a bit risky as the flash delete could be triggered by accident

In my opinion the idea described in the initial post is the more robust solution

**Comment by sfyip** [comment]
I see. The mechanism looks like this, right?
http://www.fourwalledcubicle.com/files/LUFA/Doc/120730/html/_page__software_bootloader_start.html

Thanks for providing the pull request :)
